## Connect Pandas with postgres and query the table using python

In [ ]:
from sqlalchemy import create_engine
import pandas as pd

# create a connection to the database
engine = create_engine('postgresql://postgres:DBpassword@localhost:5432/DEMO_DB')

# retrieve data from the database and store it in a DataFrame
df = pd.read_sql_query("SELECT * FROM \"COVID\"", engine)


# sort the DataFrame by a specific column in descending order
df.sort_values(by='year', ascending=True, inplace=True)

In [22]:
df.head()

,dateRep,day,month,year,cases,deaths,country,geoId,countryterritoryCode,popData2019,continentExp
22229,2019-12-31,31,12,2019,0,0,Germany,DE,DEU,83019213.0,Europe ...
58377,2019-12-31,31,12,2019,0,0,United_Arab_Emirates,AE,ARE,9770526.0,Asia ...
47268,2019-12-31,31,12,2019,0,0,Russia,RU,RUS,145872260.0,Europe ...
46570,2019-12-31,31,12,2019,0,0,Qatar,QA,QAT,2832071.0,Asia ...
55275,2019-12-31,31,12,2019,0,0,Taiwan,TW,CNG1925,23773881.0,Asia ...

In [23]:
df.shape

(61900, 11)

In [37]:
#using query
df_DE = df.query('country == "Germany" & year >= 2020')
df_DE

,dateRep,day,month,year,cases,deaths,country,geoId,countryterritoryCode,popData2019,continentExp
21926,2020-10-29,29,10,2020,16774,89,Germany,DE,DEU,83019213.0,Europe ...
21927,2020-10-28,28,10,2020,14964,85,Germany,DE,DEU,83019213.0,Europe ...
21928,2020-10-27,27,10,2020,11409,42,Germany,DE,DEU,83019213.0,Europe ...
21929,2020-10-26,26,10,2020,8685,24,Germany,DE,DEU,83019213.0,Europe ...
21930,2020-10-25,25,10,2020,11176,29,Germany,DE,DEU,83019213.0,Europe ...
...,...,...,...,...,...,...,...,...,...,...,...
22099,2020-05-09,9,5,2020,1251,103,Germany,DE,DEU,83019213.0,Europe ...
22100,2020-05-08,8,5,2020,1209,147,Germany,DE,DEU,83019213.0,Europe ...
22101,2020-05-07,7,5,2020,1284,123,Germany,DE,DEU,83019213.0,Europe ...
22102,2020-05-06,6,5,2020,947,165,Germany,DE,DEU,83019213.0,Europe ...
22134,2020-04-04,4,4,2020,6082,141,Germany,DE,DEU,83019213.0,Europe ...

In [36]:
# Usinf loc
# filter the DataFrame by column 'Country' and value 'Germany', and column 'Year' and value >2010
df_DE = df.loc[(df['country'] == 'Germany') & (df['year'] >= 2020)]

#print the filtered data
print(df_DE)

          dateRep  day  month  year  cases  deaths  country geoId  \
21926  2020-10-29   29     10  2020  16774      89  Germany    DE
21927  2020-10-28   28     10  2020  14964      85  Germany    DE
21928  2020-10-27   27     10  2020  11409      42  Germany    DE
21929  2020-10-26   26     10  2020   8685      24  Germany    DE
21930  2020-10-25   25     10  2020  11176      29  Germany    DE
...           ...  ...    ...   ...    ...     ...      ...   ...
22099  2020-05-09    9      5  2020   1251     103  Germany    DE
22100  2020-05-08    8      5  2020   1209     147  Germany    DE
22101  2020-05-07    7      5  2020   1284     123  Germany    DE
22102  2020-05-06    6      5  2020    947     165  Germany    DE
22134  2020-04-04    4      4  2020   6082     141  Germany    DE

      countryterritoryCode  popData2019  \
21926                  DEU   83019213.0
21927                  DEU   83019213.0
21928                  DEU   83019213.0
21929                  DEU   83019213.0
21930                  DEU   83019213.0
...                    ...          ...
22099                  DEU   83019213.0
22100                  DEU   83019213.0
22101                  DEU   83019213.0
22102                  DEU   83019213.0
22134                  DEU   83019213.0

                                            continentExp
21926  Europe                                        ...
21927  Europe                                        ...
21928  Europe                                        ...
21929  Europe                                        ...
21930  Europe                                        ...
...                                                  ...
22099  Europe                                        ...
22100  Europe                                        ...
22101  Europe                                        ...
22102  Europe                                        ...
22134  Europe                                        ...

[349 rows x 11 columns]